import Navbar from "./NavBar";
import Logo  from "./Logo";
import Menu  from "./Menu";
import Footer from "./Footer";
import Hero from "./Hero";
import Card from "./Card";
import PopUp from "./PopUp";
import EasyLoan from "./EasyLoan";
import LandingPage from "./LandingPage";
import Youtube from "./youtube";
import Chat from "./chat";
import Queries from "./queries";
export {Navbar,Logo,Menu,Footer,Hero,Card,PopUp,EasyLoan,LandingPage,Youtube,Chat,Queries};